### PR TITLE
feat: Add k8s node config & init container support

### PR DESCRIPTION
**Pull request by jsotelo**
This is needed to install datahub into more secure/controlled kubernetes clusters.

### CODE REVIEW

**Comment by dexter-mh-lee** [comment]
@jsotelo There are more deployment.yaml files under subcharts. Do you need to add it to those as well?

**Comment by jsotelo** [comment]
> @jsotelo There are more deployment.yaml files under subcharts. Do you need to add it to those as well?

The deployment.yaml files in subcharts already support node config and init containers. This PR should make the rest consistent.

**Comment by dexter-mh-lee** [comment]
Code looks good! You have to upgrade chart version though. It is required on any changes.

**Comment by jsotelo** [comment]
> Code looks good! You have to upgrade chart version though. It is required on any changes.

My bad. Done now thanks!

**Review by dexter-mh-lee — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
