### PR TITLE
feat(prerequisites): add postgresql to prerequistes Helm chart as an optional dependency

### PR DESCRIPTION
**Pull request by Masterchen09**
This PR adds the postgresql chart from the Bitnami chart repository as an optional and by default disabled dependency to the prerequisites Helm chart. Additionally I have added some example configuration to the values.yaml of the datahub Helm chart for documentation purposes (as far as I know the usage of PostgreSQL is not documented anywhere, as I had to search the repository for the [correct values](https://github.com/datahub-project/datahub/blob/master/docker/datahub-gms/env/docker.postgres.env) etc.).

I am not sure if this should be part of the official Helm charts, but as I wanted to use PostgreSQL in my local deployment and I already changed the charts accordingly, maybe others also want to use it and do not want to do the work twice.

If this PR is merged, we could also add some documentation [here](https://datahubproject.io/docs/deploy/kubernetes/), to explain how to use PostgreSQL, etc.

See also issue #49.

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by Wilderone** [comment]
Hi! Any new about this PR? Maybe smth i can help with? Really useful feature

**Comment by chgl** [comment]
The failing action is most likely a result of https://github.com/bitnami/charts/issues/10833 and should work now when rebasing on master.

**Comment by Masterchen09** [comment]
I have rebased the branch on master, now the checks are passing.

**Review by anshbansal — APPROVED** [review]
LGTM

**Pull request merged**
