### PR TITLE
feat: add gms hostname

### PR DESCRIPTION
**Pull request by travis-cook-sfdc**
Why?
Helm charts rely on Pod DNS.  However, if pods need to communicate with GMS another way, it's not
possible.  Currently, te gms hostname is controlled via `{{ printf "%s-%s" .Release.Name "datahub-gms" }}`

What?
- Define `datahub.gms.host` in `_helpers.tpl`. It is `.Values.global.datahub.gms.host` if exists. Else, fallback `{{ printf "%s-%s" .Release.Name "datahub-gms" }}`

- Update references of the GMS host name across charts to use the helper

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by david-leifker** [comment]
There is an alternative PR that I will work on today to achieve this. I think there might be a case or two we need to address yet. This is essentially the same approach though, to allow overriding the hostname for GMS. Thank you, I'll leave this PR open for now but will post a slightly different one.

**Comment by david-leifker** [comment]
Ok, so the primary difference is another level of override. Adding the global setting, but then also allowing say the actions pod to use a different host per subchart as well before the default. See this [PR](https://github.com/acryldata/datahub-helm/pull/406).

**Comment by david-leifker** [comment]
Closing for this alternative implementation https://github.com/acryldata/datahub-helm/pull/406

**Comment by travis-cook-sfdc** [comment]
Makes sense to me.  Thanks for the quick resolution!  This will work great for us

**Pull request closed without merging**
