### PR TITLE
feat(datahub-frontend): Option to configure OIDC auth easily

### PR DESCRIPTION
**Pull request by tomas-kubin**
## 🥅 Goal
Add an option to configure optional OIDC authentication to **datahub-frontend** subchart.

## 🔍 Details
This is already achievable by passing [appropriate values](https://datahubproject.io/docs/authentication/guides/sso/configure-oidc-react#2-configure-datahub-frontend-server) to `datahub-fronend.extraEnvs`:
```yaml
datahub-frontend:
  extraEnvs:
    - name: AUTH_OIDC_ENABLED
      value: "true"
    - name: AUTH_OIDC_CLIENT_ID
      value: your-client-id
    - name: AUTH_OIDC_CLIENT_SECRET
      value: your-client-secret
    - name: AUTH_OIDC_DISCOVERY_URI
      value: https://accounts.google.com/.well-known/openid-configuration
    - name: AUTH_OIDC_BASE_URL
      value: your-datahub-url
    - name: AUTH_OIDC_SCOPE
      value: "openid profile email"
    - name: AUTH_OIDC_USER_NAME_CLAIM
      value: email
    - name: AUTH_OIDC_USER_NAME_CLAIM_REGEX
      value: ([^@]+)
```

This PR makes it more straightforward and readable with new `datahub-frontend.oidcAuthentication` config:
```yaml
datahub-frontend:
  oidcAuthentication:
    enabled: true
    provider: google
    clientId: my-client-id
    clientSecret: my-client-secret
```

Can use any of the three supported providers: [google](https://datahubproject.io/docs/authentication/guides/sso/configure-oidc-react-google), [okta](https://datahubproject.io/docs/authentication/guides/sso/configure-oidc-react-okta), or [azure](https://datahubproject.io/docs/authentication/guides/sso/configure-oidc-react-azure).

## 🧪 Testing
Locally rendering using `helm template . > preview.yaml`.

<details>
<summary>provider: google</summary>

### provider: google
Extending values.yaml:
```yaml
datahub-frontend:
  ...
  oidcAuthentication:
    enabled: true
    provider: google
    clientId: MYCLIENTID
    clientSecret: MYCLIENTSECRET
```
The preview now contains these in `spec.template.spec.containers[0].env`:
```yaml
            - name: AUTH_OIDC_ENABLED
              value: "true"
            - name: AUTH_OIDC_CLIENT_ID
              value: MYCLIENTID
            - name: AUTH_OIDC_CLIENT_SECRET
              value: MYCLIENTSECRET
            - name: AUTH_OIDC_BASE_URL
              value: https://chart-example.local
            - name: AUTH_OIDC_DISCOVERY_URI
              value: https://accounts.google.com/.well-known/openid-configuration
            - name: AUTH_OIDC_SCOPE
              value: "openid profile email"
            - name: AUTH_OIDC_USER_NAME_CLAIM
              value: email
            - name: AUTH_OIDC_USER_NAME_CLAIM_REGEX
              value: ([^@]+)
```

This provider has also been to tested to actually work -> triggering Google login screen and actually signing an internal google user.
</details>

<details>
<summary>provider: okta</summary>

### provider: okta
Extending values.yaml:
```yaml
datahub-frontend:
  ...
  oidcAuthentication:
    enabled: true
    provider: okta
    clientId: MYCLIENTID
    clientSecret: MYCLIENTSECRET
    oktaDomain: MYOKTADOMAIN
```
The preview now contains:
```yaml
            - name: AUTH_OIDC_ENABLED
              value: "true"
            - name: AUTH_OIDC_CLIENT_ID
              value: MYCLIENTID
            - name: AUTH_OIDC_CLIENT_SECRET
              value: MYCLIENTSECRET
            - name: AUTH_OIDC_BASE_URL
              value: https://chart-example.local
            - name: AUTH_OIDC_DISCOVERY_URI
              value: https://MYOKTADOMAIN/.well-known/openid-configuration
            - name: AUTH_OIDC_SCOPE
              value: "openid profile email groups"
```
</details>

<details>
<summary>provider: azure</summary>

### provider: azure
Extending values.yaml:
```yaml
datahub-frontend:
  ...
  oidcAuthentication:
    enabled: true
    provider: azure
    clientId: MYCLIENTID
    clientSecret: MYCLIENTSECRET
    azureTenantId: MYAZURETENANTID
```
The preview now contains:
```yaml
            - name: AUTH_OIDC_ENABLED
              value: "true"
            - name: AUTH_OIDC_CLIENT_ID
              value: MYCLIENTID
            - name: AUTH_OIDC_CLIENT_SECRET
              value: MYCLIENTSECRET
            - name: AUTH_OIDC_BASE_URL
              value: https://chart-example.local
            - name: AUTH_OIDC_DISCOVERY_URI
              value: https://login.microsoftonline.com/MYAZURETENANTID/v2.0/.well-known/openid-configuration
            - name: AUTH_OIDC_SCOPE
              value: "openid profile email"
```
</details>

## ✔️ Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (no related issue)
- [x] Tests for the changes have been added/updated
- [x] Docs related to the changes have been added/updated

### CODE REVIEW

**Comment by pedro93** [comment]
Hello @tomas-kubin 

Thank you for this PR! Could I ask you to bump the frontend chart yaml so that the linter passes?

**Comment by tomas-kubin** [comment]
@pedro93 Chart versions were bumped. The linter should now pass.

**Comment by tomas-kubin** [comment]
@pedro93 Can you please rerun the workflow for this PR so that we see if the linter passes? I cannot do it as I'm first-time contributor. Thanks!

**Comment by tomas-kubin** [comment]
@pedro93 Sorry, I missed a version. Now it should be fixed. Could you please run it once again?

**Comment by tomas-kubin** [comment]
@pedro93 Thanks, the linter passed. Could you please do a code review for this PR?

**Review by novotl — APPROVED** [review]
Thanks @tomas-kubin we will benefit from this new feature 🙏

**Review by anshbansal — APPROVED** [review]
LGTM

**Pull request merged**
