### PR TITLE
fix(neo4j): enable APOC plugin

### PR DESCRIPTION
**Pull request by lix-mms**
Prerequisite change for https://github.com/datahub-project/datahub/pull/8687

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] ~~Links to related issues (if applicable)~~
- [x] ~~Tests for the changes have been added/updated (if applicable)~~
- [x] ~~Docs related to the changes have been added/updated (if applicable)~~

### CODE REVIEW

**Comment by lix-mms** [comment]
Reference to example how an env var is added based on the new chart structure:
https://github.com/neo4j/helm-charts/tree/dev/examples/bloom-gds-license#deploy-neo4j-gds-and-bloom-with-license-files

**Comment by RyanHolstien** [comment]
Hiya @lix-mms 😄 Thanks for the contribution, do you mind updating the chart version on this PR?

**Comment by lix-mms** [comment]
@RyanHolstien My pleasure to contribute! I updated the version accordingly. 😊

**Comment by RyanHolstien** [comment]
Ah sorry! I should have been more specific, since this is a change to the prerequisites chart it has to be an update to the datahub-prerequisites Chart.yaml.

**Comment by lix-mms** [comment]
@RyanHolstien Oh... right! Thanks for the catch!

Fixed it accordingly 😄

**Review by RyanHolstien — APPROVED** [review]

**Comment by RyanHolstien** [comment]
Thank you! 😄

**Pull request merged**
