### PR TITLE
fix(actions): update datahub actions default version

### PR DESCRIPTION
**Pull request by DSchmidtDev**
Updated the default version according to actual releases https://github.com/acryldata/datahub-actions/releases

### CODE REVIEW

**Comment by anshbansal** [comment]
The chart version also need to be updated otherwise this will not work.

**Comment by DSchmidtDev** [comment]
Ah thought it can go in the next release but updated the chart version now :)

**Comment by DSchmidtDev** [comment]
@anshbansal @iprentic  someone can review this?

**Comment by DSchmidtDev** [comment]
@shirshanka maybe you can approve this? :)

**Comment by pedro93** [comment]
@DSchmidtDev can you please resolve the merge conflict? I will approve after.

**Comment by DSchmidtDev** [comment]
resolved the merge conflict

**Comment by OneCyrus** [comment]
stumbled across the same outdated actions image. any chance this can get merged? @pedro93

**Review by pedro93 — APPROVED** [review]

**Comment by pedro93** [comment]
Sorry about the delay here folks. Approved the pr.

**Pull request merged**
