### PR TITLE
Delete jobs once they succeed

### PR DESCRIPTION
**Pull request by csp33**
## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Review by anshbansal — COMMENTED** [review]
Can you explain why? Not deleting the jobs immediately can help in debugging setup related issues.

**Comment by csp33** [comment]
Sure @anshbansal !
First of all, completed pods would be deleted **only if they are successful**, so there shouldn't be nothing to debug there.
Other Open Source projects (such as Apache Airflow) delete their jobs once completed, as they are no longer useful (keep in mind that they won't be deleted if they fail). Example: https://github.com/apache/airflow/blob/main/chart/templates/jobs/create-user-job.yaml#L44

**Comment by pedro93** [comment]
Hello @csp33 

For feature completeness have you considered also modifying the `datahub-ingestion-cron` sub chart? It is a template that will generate CronJobs which in turn trigger Jobs.

Follow-up, K8s determines job successful if status code is 0 right? This means that DataHub's job would need to throw a non-zero code if some exception was thrown that might need further investigation. I not 100% sure all DataHub's job meet the requirement.

**Comment by csp33** [comment]
Hi @pedro93 
`datahub-ingestion-cron` is a **cronjob**, a job that is periodically executed.
The files I am modifying are **hooks**. That means they are executed **only when installing/updating** the app.

Cronjobs are usually maintained because they can be used to trace their executions. However, hooks are executed only when installing/updating the app, so they don't need to be traced once they success.

More info: https://helm.sh/docs/topics/charts_hooks/

**Comment by csp33** [comment]
Regarding the 0 exit code, I think none of the hooks I modified would return a 0 exit code if they fail

**Comment by csp33** [comment]
Hi @anshbansal 
Can we merge this PR?

**Comment by anshbansal** [comment]
hey @csp33 
Thanks for the contribution.

We discussed this internally and it would be better if we added `ttlSecondsAfterFinished` https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/ as a configuration option instead of deleting on completion. That achieves the same result where resources are cleaned up but it allows us to keep the job for some time which can be useful for debugging purposes.

**Comment by csp33** [comment]
Hi @anshbansal 
It's done

**Pull request closed without merging**
