### PR TITLE
feat(cron): Adding more parameters to ingestion-cron

### PR DESCRIPTION
**Pull request by miguelbirdie**
This PR enabling to users to set up different parameters of the cronjob/job in the ingestion process. In particular, we will be able to configure the following parameters:
- `concurrencyPolicy`
- `successfulJobsHistoryLimit `
- `failedJobsHistoryLimit `
- `backoffLimit `
- `restartPolicy`

## Checklist
- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Review by benw-at-birdie — APPROVED** [review]

**Comment by benw-at-birdie** [comment]
Super!

**Review by david-leifker — APPROVED** [review]

**Comment by david-leifker** [comment]
Thank you!!

**Comment by david-leifker** [comment]
@miguelbirdie - Just looking to bump the version of the chart [here](https://github.com/birdiecare/datahub-helm/pull/2/files)

**Comment by miguelbirdie** [comment]
> @miguelbirdie - Just looking to bump the version of the chart [here](https://github.com/birdiecare/datahub-helm/pull/2/files)

Thanks @david-leifker! It's already merged 🎉

**Pull request merged**
