### PR TITLE
feat(elasticsearch-setup): Add support for insecure curl connections

### PR DESCRIPTION
**Pull request by BogdanAntoniu78**
Complementing https://github.com/datahub-project/datahub/pull/5887 to introduce insecure curl connectivity option. 

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Review by anshbansal — CHANGES_REQUESTED** [review]
Please add default value for these in `values.yaml` file in this repostiroy. Also, need to increase chart version in `Chart.yaml`

**Comment by BogdanAntoniu78** [comment]
Sure. Thank you for the comment!

**Review by anshbansal — COMMENTED** [review]
Blocked until https://github.com/datahub-project/datahub/pull/5887 is merged in

**Review by anshbansal — APPROVED** [review]
LGTM

**Pull request merged**
