### PR TITLE
feat(datahub-upgrade): Restore Indices Resources

### PR DESCRIPTION
**Pull request by HunterEl**
This PR adds the ability for end-users to specify resource requests and limits
for the datahub upgrade job 'restore indices'. This is needed for situations
where the restore indices job will OOM due to a large backfill of data. I've
seen this happening with our deployment of datahub and am unable to tune
the resources for the restore indices job because the current requests
and limits are hard-coded.

In addition, bumps chart version to 0.2.90

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by anshbansal** [comment]
@HunterEl If you can update the chart version per latest master we can merge this PR in.

**Review by anshbansal — APPROVED** [review]
LGTM

**Comment by xiphl** [comment]
the appVersion for the app shouldnt have been incremented to 0.8.44... 
0.8.44 is only released on 1 Sept.

**Comment by anshbansal** [comment]
Yes this problem was noticed later on. But given we have already released later versions it should be fine.

**Pull request merged**
