### PR TITLE
feat(charts): Support Rancher Catalog (#130)

### LINKED ISSUE #130: Support the Rancher Charts
**Is your feature request related to a problem? Please describe.**
We use [Rancher](https://rancher.com/) to deploy DataHub.  
Rancher has [Rancher Charts](https://www.rancher.co.jp/docs/rancher/v2.x/en/catalog/custom/creating/#chart-types) that is extension of Helm charts. 
Using Rancher Charts, we can edit (overwrite) `values.yaml` from the UI.

**Describe the solution you'd like**
To support the Rancher Charts, we need to add `questions.yaml` and `app-readme.md`.  
And I created these files for `datahub` chart. Please refer to Additional context. 
I will create these for `prerequisites` chart.

**Describe alternatives you've considered**
n/a

**Additional context**
This is the screenshot of Rancher UI.  
Users can set the values when launch or upgrade App.  
Also, it is possible to specify a private registry (like `registry.local`) in an air-gap environment for the `Image Registry`.

image

sample of `questions.yaml`: 

```yaml
---
categories:
  - datahub
  - datacatalog
questions:
  - variable: datahub-gms.enabled
    default: true
    type: boolean
    label: Enable GMS
    group: "datahub-gms"
    description: "Enable GMS"
    show_subquestion_if: true
    subquestions:
      - variable: datahub-gms.image.registry
        required: true
        default: "docker.io"
        type: string
        label: datahub-gms Image Registry
        group: "datahub-gms"
        description: "Image registry for datahub-gms"
      - variable: datahub-gms.image.repository
        required: true
        default: "linkedin/datahub-gms"
        type: string
        label: datahub-gms Image Repository
        group: "datahub-gms"
        description: "Image repository for datahub-gms"
      - variable: datahub-gms.image.tag
        required: true
        default: "v0.8.38"
        type: string
        label: datahub-gms Image Tag
        group: "datahub-gms"
        description: "Image tag for datahub-gms"
  - variable: datahub-frontend.enabled
    default: true
    type: boolean
    label: Enable Frontend
    group: "datahub-frontend"
    description: "Enable Frontend"
    show_subquestion_if: true
    subquestions:
      - variable: datahub-frontend.image.registry
        required: true
        default: "docker.io"
        type: string
        label: datahub-frontend Image Registry
        group: "datahub-frontend"
        description: "datahub-frontend Image Registry"
      - variable: datahub-frontend.ingress.enabled
        default: false
        type: boolean
        label: datahub-frontend Ingress
        group: "datahub-frontend"
        description: "Set up ingress to expose react front-end"
  - variable: acryl-datahub-actions.enabled
    default: true
    type: boolean
    label: Enable Actions
    group: "acryl-datahub-actions"
    description: "Enable Actions"
    show_subquestion_if: true
    subquestions:
      - variable: acryl-datahub-actions.image.registry
        required: true
        default: "docker.io"
        type: string
        label: acryl-datahub-actions Image Registry
        group: "acryl-datahub-actions"
        description: "acryl-datahub-actions Image Registry"
      - variable: acryl-datahub-actions.image.repository
        required: true
        default: "public.ecr.aws/datahub/acryl-datahub-actions"
        type: string
        label: acryl-datahub-actions Image Repository
        group: "acryl-datahub-actions"
        description: "Image repository for acryl-datahub-actions"
      - variable: acryl-datahub-actions.image.tag
        required: true
        default: "v0.0.1-beta.13"
        type: string
        label: acryl-datahub-actions Image Tag
        group: "acryl-datahub-actions"
        description: "Image tag for acryl-datahub-actions"
...
```

### PR DESCRIPTION
**Pull request by k-ebu**
## Refference

- [Rancher Overview](https://www.rancher.co.jp/docs/rancher/v2.x/en/overview/)
- [Catalogs and Apps](https://www.rancher.co.jp/docs/rancher/v2.x/en/catalog/)
- [Creating Custom Catalogs Apps](https://www.rancher.co.jp/docs/rancher/v2.x/en/catalog/custom/creating/)

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
  - #130 
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

Closes #130

### CODE REVIEW

**Comment by k-ebu** [comment]
@dexter-mh-lee Thank you.

I don't think that all variables in `values.yml` need to be able to be changed from the GUI.

For example, the `Image repository` can be changed from the GUI because we sometimes use Private Registry, but the `Image tag` input field was removed in the following commit because it is operated to be changed by the developer when the Chart is released.

[b894723](https://github.com/acryldata/datahub-helm/pull/131/commits/b89472312f3fba5eb7ded3c22ce776f8b615e811)

If users want to change the values in more detail, Rancher has the feature to edit the YAML file directly.
I think it is better to set items in `questions.yml` that are commonly changed, and edit `questions.yml` only when such items are newly added.

**Comment by k-ebu** [comment]
@dexter-mh-lee 
Could you review it?

**Comment by eburairu** [comment]
ping

**Comment by szalai1** [comment]
hi @eburairu thanks for the contribution, but we feel the team doesn't have the capacity to keep these files updated and provide maintenance. 
couldn't this part of a separate community driven repo maintained by you?

**Pull request closed without merging**
