### PR TITLE
feat: Add custom label support for ServiceMonitor in DataHub charts (#449)

### LINKED ISSUE #449: Enhance DataHub Helm Charts to Apply extraLabels to ServiceMonitor Resources for Improved Prometheus Integration
**Is your feature request related to a problem? Please describe.**
The existing DataHub Helm charts for `datahub-frontend` and `datahub-gms` already support the specification of `extraLabels` in the `values.yaml` file, which can be applied to `Service` and `Deployment` resources. However, this functionality is not currently extended to `ServiceMonitor` resources, which poses a challenge for integrating with Prometheus in environments that require specific labeling conventions for service discovery and monitoring. Our Prometheus setup, for example, relies on specific labels for scraping metrics, and the inability to apply these labels directly to `ServiceMonitor` resources through the Helm chart necessitates manual post-deployment adjustments or maintaining a customized version of the chart.

**Describe the solution you'd like**
I propose enhancing the DataHub Helm charts for `datahub-frontend` and `datahub-gms` to ensure that `extraLabels` defined in the `values.yaml` are also applied to `ServiceMonitor` resources. This can be achieved by including a similar templating block as used for `Service` and `Deployment` resources within the `ServiceMonitor` definition:

```yaml
{{- if and .Values.serviceMonitor.create .Values.global.datahub.monitoring.enablePrometheus -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-%s" .Release.Name "datahub-frontend" }}
  labels:
    {{- include "datahub-frontend.labels" . | nindent 4 }}
    {{- range $key, $val := .Values.extraLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
# other staff
```
Implementing this change would align the handling of `extraLabels` across different resource types within the chart, providing users with a consistent and flexible way to apply labels that meet their operational and monitoring needs.

**Describe alternatives you've considered**
The current workaround involves manually editing the `ServiceMonitor` resources after deployment to include the required labels, or modifying and maintaining a fork of the Helm chart with our specific adjustments. Both approaches are less than ideal, as they either introduce manual steps that complicate automation or result in divergence from the community-driven chart, complicating updates and maintenance.

**Additional context**
The inclusion of `extraLabel`s in `Service` and `Deployment` definitions within the DataHub Helm charts demonstrates a commitment to flexibility and customization. Extending this functionality to `ServiceMonitor` resources would further enhance the utility and user-friendliness of the chart, facilitating seamless integration with monitoring tools and adherence to diverse operational practices.

### PR DESCRIPTION
**Pull request by Squallman**
This pull request adds support for specifying custom labels for `ServiceMonitor` resources via the `values.yaml` file in the DataHub Helm charts. This enhancement enables seamless integration with Prometheus by allowing for the application of organization-specific labeling conventions directly during the Helm chart deployment process.

## Motivation and Context
Custom label support for `ServiceMonitor` resources aligns with existing customization capabilities for Service and Deployment resources within the DataHub Helm charts, addressing a gap in the configuration flexibility needed for comprehensive monitoring setups. This update facilitates more precise service discovery and monitoring configurations, particularly in environments where Prometheus's service discovery mechanisms rely heavily on specific label sets.

## How Has This Been Tested?
- Manual tests deploying the updated Helm chart in a sandbox environment with various custom label configurations specified in `values.yaml`.
- Verification steps included inspecting the deployed `ServiceMonitor` resources for the presence of custom labels and ensuring that Prometheus could discover and scrape metrics from services associated with those labels.
- Automated tests were added to validate the Helm chart's template logic for injecting custom labels into `ServiceMonitor` resources.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

## Related Issue(s)
Resolves #449

### CODE REVIEW

**Review by darnaut — APPROVED** [review]

**Comment by darnaut** [comment]
@Squallman please rebase and bump the versions for the charts being modified

**Comment by Masterchen09** [comment]
@Squallman As we already use your PR within an internal fork of the datahub-helm chart, I noticed, that your changes only affect the service monitors for the datahub-gms and datahub-frontend subcharts, but not the datahub-mae-consumer and datahub-mce-consumer subcharts:

https://github.com/acryldata/datahub-helm/blob/master/charts/datahub/subcharts/datahub-mce-consumer/templates/servicemonitor.yaml

https://github.com/acryldata/datahub-helm/blob/master/charts/datahub/subcharts/datahub-mae-consumer/templates/servicemonitor.yaml

I think it would make sense to also allow to specify custom labels for theses two service monitors. 😊

**Comment by Squallman** [comment]
Hi @Masterchen09,

I've updated my PR to include the implementation for custom labels in the service monitors for both the datahub-mae-consumer and datahub-mce-consumer subcharts. Could you please review the changes and approve the workflow?

Thank you! 😊

**Comment by Masterchen09** [comment]
Hi @Squallman,

thank you for adding the custom labels also for the service monitors of the mae- and mce-consumer! 😊

Unfortunately I cannot review or approve anything here as I am not part of the Acryldata team - I am "only" a contributor like you. 😅

**Pull request merged**
