### PR TITLE
Fix: defaultCliVersion in values.yaml is not up to date with latest cli version

### PR DESCRIPTION
**Pull request by TonyOuyangGit**
This PR is a quick fix to datahub/values.yaml to update `defaultCliVersion` to use `v0.10.2` to align with the latest changes, otherwise, the ingestion run will still use `v0.10.0` as the default cli version.

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Review by jinlintt — APPROVED** [review]
Thank you @TonyOuyangGit

**Comment by justmike1** [comment]
why not just deleting this as a value and using `{{ .Values.global.datahub.version }}` Instead?

**Comment by justmike1** [comment]
> > why not just deleting this as a value and using `{{ trimPrefix "v" .Values.global.datahub.version }}` Instead? @jinlintt
> 
> @justmike1 For backward compatibility, we shouldn't delete any variables. Otherwise, for people who rely on this variable, it will stop working unexpectedly.

I see, I will also take this into consideration on my other PR #297

**Comment by jinlintt** [comment]
@pedro93 could you take a look?
We know that we could set this in our `values.yaml` file. But if the chart has the matching cli version, then we have one less thing to worry and maintain.

We don't care as much when you released new version of CLI, but the chart doesn't match unless it has something important.

**Comment by TonyOuyangGit** [comment]
Closing this PR, it's already updated by latest release

**Pull request closed without merging**
